### PR TITLE
Fix/dependency cleanup

### LINKED ISSUE #117: Cleanup dependency mess (See #115)

### PR DESCRIPTION
**Pull request by JesusMcCloud**
fixes #117 (requires signum update only for new signature of conventions)

### CODE REVIEW

**Comment by JesusMcCloud** [comment]
(also: no changelog, because this is just internal and should have absolutely zero effect to outside consumers of this lib)

File: vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/KeyMaterial.kt [hunk 1]
```diff
@@ -12,6 +12,7 @@ import at.asitplus.signum.supreme.asKmmResult
 import at.asitplus.signum.supreme.sign.EphemeralKey
 import at.asitplus.signum.supreme.sign.Signer
 import io.github.aakira.napier.Napier
+import kotlinx.coroutines.Job
```
Comment (nodh) [inline vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/KeyMaterial.kt:15]: shouldn't be here

**Review by nodh — APPROVED** [review]
